// <auto-generated />
using DemoAPI.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoAPI.Migrations
{
    [DbContext(typeof(MSSQLContext))]
    [Migration("20231217132903_InitialCountriesDB")]
    partial class InitialCountriesDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoAPI.Models.Border", b =>
                {
                    b.Property<string>("BorderName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryModelCommonName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BorderName");

                    b.HasIndex("CountryModelCommonName");

                    b.ToTable("Border");
                });

            modelBuilder.Entity("DemoAPI.Models.CountryModel", b =>
                {
                    b.Property<string>("CommonName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommonName");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DemoAPI.Models.Border", b =>
                {
                    b.HasOne("DemoAPI.Models.CountryModel", null)
                        .WithMany("Borders")
                        .HasForeignKey("CountryModelCommonName");
                });

            modelBuilder.Entity("DemoAPI.Models.CountryModel", b =>
                {
                    b.Navigation("Borders");
                });
#pragma warning restore 612, 618
        }
    }
}
